// Seed-data voor cc_test_customers — bewust géén echte klantnamen.
// 6 fictieve voorbeelden verspreid over de pipeline-statussen zodat de
// pipeline-view direct iets toont. Idempotent geladen door ensureCustomersSeeded.

import type { TestCustomerInput } from './types';

export const SEED_CUSTOMERS: TestCustomerInput[] = [
  {
    companyName: 'Bakkerij De Korenbloem (fictief)',
    contactPerson: 'Linda V.',
    website: 'https://example.bakkerij.nl',
    companyType: 'Lokale bakkerij',
    status: 'Idee / mogelijke klant',
    owner: 'Niels',
    notes: 'Komt uit netwerk Niels. Klein team, lokale bezorging.',
    mainProblems: 'Veel telefoontjes over openingstijden en bestelroutes.',
    caseStudyPotential: true,
  },
  {
    companyName: 'Praktijk Voorhof (fictief)',
    contactPerson: 'Dr. P. Bakker',
    website: 'https://example.huisarts.nl',
    companyType: 'Huisartsenpraktijk',
    status: 'Nog benaderen',
    owner: 'Niels',
    nextAction: 'Mailen na blog-launch widget-demo',
    mainProblems: 'Veel herhaalvragen over recepten en afspraken.',
    caseStudyPotential: true,
  },
  {
    companyName: 'Studio Driehoek (fictief)',
    contactPerson: 'M. Janssen',
    website: 'https://example.creatives.nl',
    companyType: 'Design studio',
    status: 'Benaderd',
    owner: 'Niels',
    lastContactDate: '2026-05-08',
    nextAction: 'Follow-up call inplannen',
    notes: 'Geïnteresseerd, wacht op nieuwe homepage-content.',
    caseStudyPotential: false,
  },
  {
    companyName: 'Sport & Health (fictief)',
    contactPerson: 'T. de Vries',
    website: 'https://example.sport.nl',
    companyType: 'Sportschool',
    status: 'Gesprek gepland',
    owner: 'Samen',
    lastContactDate: '2026-05-12',
    nextAction: 'Demo voorbereiden — focus op lidmaatschap-FAQ',
    mainProblems: 'Front-desk krijgt veel basisvragen over openingstijden, abonnementen.',
    caseStudyPotential: true,
  },
  {
    companyName: 'TextielHub (fictief)',
    contactPerson: 'A. el Idrissi',
    website: 'https://example.textiel.nl',
    companyType: 'B2B textiel groothandel',
    status: 'Demo gegeven',
    owner: 'Sebastiaan',
    lastContactDate: '2026-05-15',
    nextAction: 'Pricing-voorstel sturen + test-omgeving openzetten',
    notes: 'Demo positief; vraag over multi-language support.',
    mainProblems: 'Engelstalige klanten, productcatalogus van 800+ SKUs.',
    caseStudyPotential: true,
  },
  {
    companyName: 'AdviesBureau Noord (fictief)',
    contactPerson: 'F. Bos',
    website: 'https://example.advies.nl',
    companyType: 'Zakelijke dienstverlening',
    status: 'Testklant actief',
    owner: 'Samen',
    lastContactDate: '2026-05-17',
    nextAction: 'Wekelijkse feedback-call (woensdag)',
    notes: 'Eerste actieve testklant. Widget draait sinds 2026-05-10.',
    mainProblems: 'Veel intake-vragen via telefoon — willen offload naar widget.',
    caseStudyPotential: true,
  },
];
