// Seed data — letterlijk uit goal-prompt §19 (Sebastiaan, Niels, Samen, Nog toe te wijzen).
//
// Idempotent: ensureSeeded() in storage.ts checkt of cc_tasks leeg is voor
// insert. Eénmalig op eerste load van /commandcenter ingevoerd. Daarna mag
// vrij gemuteerd worden — opnieuw seeden gebeurt niet automatisch.

import type { TaskInput } from './types';

export const SEED_TASKS: TaskInput[] = [
  // -----------------------------------------------------------------------
  // Sebastiaan — RAG & AI kwaliteit
  // -----------------------------------------------------------------------
  {
    title: 'Evaluatieset maken met 50 echte klantvragen',
    owner: 'Sebastiaan',
    status: 'Deze week',
    priority: 'P1',
    roadmapPhase: 'v0.6',
    projectArea: 'Evaluaties / testdata',
    nextAction: 'Verzamel 50 representatieve vragen en verwachte antwoorden.',
    impact: 'Hoog',
    effort: 'Middel',
  },
  {
    title: 'Fallback verbeteren wanneer informatie ontbreekt',
    owner: 'Sebastiaan',
    status: 'Deze week',
    priority: 'P1',
    roadmapPhase: 'v0.6',
    projectArea: 'RAG & AI kwaliteit',
    nextAction: 'Zorg dat de chatbot duidelijk zegt wanneer informatie niet in de kennisbank staat.',
    impact: 'Hoog',
    effort: 'Middel',
  },
  {
    title: 'Bronselectie verbeteren',
    owner: 'Sebastiaan',
    status: 'Bezig',
    priority: 'P1',
    roadmapPhase: 'v0.6',
    projectArea: 'RAG & AI kwaliteit',
    nextAction: 'Analyseer foute antwoorden en verbeter retrieval/chunk selectie.',
    impact: 'Hoog',
    effort: 'Groot',
  },
  {
    title: 'Hallucinatiechecks toevoegen',
    owner: 'Sebastiaan',
    status: 'Backlog',
    priority: 'P2',
    roadmapPhase: 'v0.6',
    projectArea: 'RAG & AI kwaliteit',
    nextAction: 'Voeg testcases toe waarbij de bot geen antwoord mag verzinnen.',
    impact: 'Hoog',
    effort: 'Middel',
  },
  {
    title: 'Antwoordkwaliteit meten per testvraag',
    owner: 'Sebastiaan',
    status: 'Backlog',
    priority: 'P2',
    roadmapPhase: 'v0.6',
    projectArea: 'Evaluaties / testdata',
    nextAction: 'Maak scorevelden: correct, deels correct, fout, geen antwoord.',
    impact: 'Middel',
    effort: 'Middel',
  },
  // Widget
  {
    title: 'Widget responsive maken',
    owner: 'Sebastiaan',
    status: 'Backlog',
    priority: 'P2',
    roadmapPhase: 'v1',
    projectArea: 'Widget',
    nextAction: 'Test widget op desktop en mobiel.',
    impact: 'Middel',
    effort: 'Middel',
  },
  {
    title: 'Widget embed script testen',
    owner: 'Sebastiaan',
    status: 'Backlog',
    priority: 'P1',
    roadmapPhase: 'v1',
    projectArea: 'Widget',
    nextAction: 'Test of de widget op externe testsite kan draaien.',
    impact: 'Hoog',
    effort: 'Klein',
  },
  // Dashboard / Kennisbank
  {
    title: 'Basis klantdashboard maken',
    owner: 'Sebastiaan',
    status: 'Backlog',
    priority: 'P2',
    roadmapPhase: 'v1',
    projectArea: 'Dashboard',
    nextAction: 'Maak eerste dashboard met kennisbank, instellingen en usage.',
    impact: 'Middel',
    effort: 'Groot',
  },
  {
    title: 'Document upload pagina maken',
    owner: 'Sebastiaan',
    status: 'Backlog',
    priority: 'P1',
    roadmapPhase: 'v1',
    projectArea: 'Kennisbank',
    nextAction: 'Bouw upload flow voor pdf/doc bestanden.',
    impact: 'Hoog',
    effort: 'Middel',
  },
  {
    title: 'Websitecontent importeren',
    owner: 'Sebastiaan',
    status: 'Backlog',
    priority: 'P1',
    roadmapPhase: 'v1',
    projectArea: 'Kennisbank',
    nextAction: "Maak flow om websitepagina's in de kennisbank te krijgen.",
    impact: 'Hoog',
    effort: 'Groot',
  },
  // Deployment
  {
    title: 'Staging omgeving opzetten',
    owner: 'Sebastiaan',
    status: 'Backlog',
    priority: 'P2',
    roadmapPhase: 'v1',
    projectArea: 'Deployment / hosting',
    nextAction: 'Zet aparte staging omgeving klaar.',
    impact: 'Middel',
    effort: 'Middel',
  },
  {
    title: 'Error logging toevoegen',
    owner: 'Sebastiaan',
    status: 'Backlog',
    priority: 'P2',
    roadmapPhase: 'v0.6',
    projectArea: 'Bugs',
    nextAction: 'Zorg dat errors zichtbaar worden in logs/dashboard.',
    impact: 'Middel',
    effort: 'Klein',
  },

  // -----------------------------------------------------------------------
  // Niels — Sales / testklanten
  // -----------------------------------------------------------------------
  {
    title: 'Lijst met 10 mogelijke testklanten maken',
    owner: 'Niels',
    status: 'Deze week',
    priority: 'P1',
    roadmapPhase: 'v1',
    projectArea: 'Sales / testklanten',
    nextAction: 'Maak lijst met bedrijven uit netwerk die websitevragen krijgen.',
    impact: 'Hoog',
    effort: 'Klein',
  },
  {
    title: 'Eerste 3 testklanten selecteren',
    owner: 'Niels',
    status: 'Deze week',
    priority: 'P1',
    roadmapPhase: 'v1',
    projectArea: 'Sales / testklanten',
    nextAction: 'Kies de 3 meest kansrijke bedrijven voor eerste benadering.',
    impact: 'Hoog',
    effort: 'Klein',
  },
  {
    title: 'Outreach-bericht voor testklanten schrijven',
    owner: 'Niels',
    status: 'Deze week',
    priority: 'P1',
    roadmapPhase: 'v1',
    projectArea: 'Sales / testklanten',
    nextAction: 'Schrijf kort bericht waarin we gratis/laagdrempelig willen testen.',
    impact: 'Hoog',
    effort: 'Klein',
  },
  {
    title: 'Eerste 3 testklanten benaderen',
    owner: 'Niels',
    status: 'Backlog',
    priority: 'P1',
    roadmapPhase: 'v1',
    projectArea: 'Sales / testklanten',
    nextAction: 'Stuur bericht naar de 3 geselecteerde testklanten.',
    impact: 'Hoog',
    effort: 'Klein',
  },
  {
    title: 'Demo-script schrijven',
    owner: 'Niels',
    status: 'Backlog',
    priority: 'P2',
    roadmapPhase: 'v1',
    projectArea: 'Sales / testklanten',
    nextAction: 'Maak simpele structuur voor een demo van 10 minuten.',
    impact: 'Middel',
    effort: 'Klein',
  },
  {
    title: 'Feedbackformulier maken voor testklanten',
    owner: 'Niels',
    status: 'Backlog',
    priority: 'P2',
    roadmapPhase: 'v1',
    projectArea: 'Sales / testklanten',
    nextAction: 'Maak vragenlijst voor feedback na chatbot-test.',
    impact: 'Middel',
    effort: 'Klein',
  },
  {
    title: 'Testklant onboarding checklist maken',
    owner: 'Niels',
    status: 'Backlog',
    priority: 'P2',
    roadmapPhase: 'v1',
    projectArea: 'Documentatie',
    nextAction: 'Beschrijf welke info we nodig hebben om klant live te zetten.',
    impact: 'Middel',
    effort: 'Klein',
  },
  // Pricing / positionering
  {
    title: 'Concurrenten kort bekijken',
    owner: 'Niels',
    status: 'Backlog',
    priority: 'P2',
    roadmapPhase: 'v1',
    projectArea: 'Pricing / positionering',
    nextAction: 'Bekijk 5 chatbottools en noteer pricing/positionering.',
    impact: 'Middel',
    effort: 'Klein',
  },
  {
    title: 'Eerste simpele prijsvoorstel maken',
    owner: 'Niels',
    status: 'Backlog',
    priority: 'P2',
    roadmapPhase: 'v1',
    projectArea: 'Pricing / positionering',
    nextAction: 'Maak voorstel voor testklantprijs en latere standaardprijs.',
    impact: 'Middel',
    effort: 'Klein',
  },
  {
    title: 'Veelgestelde klantbezwaren opschrijven',
    owner: 'Niels',
    status: 'Backlog',
    priority: 'P2',
    roadmapPhase: 'v1',
    projectArea: 'Sales / testklanten',
    nextAction: 'Schrijf mogelijke bezwaren op zoals AI, privacy, kosten, betrouwbaarheid.',
    impact: 'Middel',
    effort: 'Klein',
  },

  // -----------------------------------------------------------------------
  // Samen
  // -----------------------------------------------------------------------
  {
    title: 'Bepalen wanneer v0.6 "goed genoeg" is',
    owner: 'Samen',
    status: 'Deze week',
    priority: 'P1',
    roadmapPhase: 'v0.6',
    projectArea: 'Product / UX',
    labels: ['decision-needed'],
    nextAction: 'Spreek acceptatiecriteria af voor v0.6.',
    impact: 'Hoog',
    effort: 'Klein',
  },
  {
    title: 'Eerste testklantprofiel bepalen',
    owner: 'Samen',
    status: 'Deze week',
    priority: 'P1',
    roadmapPhase: 'v1',
    projectArea: 'Sales / testklanten',
    labels: ['decision-needed'],
    nextAction: 'Bepaal welk type bedrijf we als eerste willen testen.',
    impact: 'Hoog',
    effort: 'Klein',
  },
  {
    title: 'Demo-flow bepalen',
    owner: 'Samen',
    status: 'Backlog',
    priority: 'P2',
    roadmapPhase: 'v1',
    projectArea: 'Product / UX',
    nextAction: 'Bepaal wat we tijdens een eerste demo wel/niet laten zien.',
    impact: 'Middel',
    effort: 'Klein',
  },
  {
    title: 'Besluiten welke features niet in v1 komen',
    owner: 'Samen',
    status: 'Backlog',
    priority: 'P1',
    roadmapPhase: 'v1',
    projectArea: 'Product / UX',
    labels: ['decision-needed'],
    nextAction: 'Maak bewuste no-go lijst voor v1.',
    impact: 'Hoog',
    effort: 'Klein',
  },
  {
    title: 'Wekelijkse check-in ritme vastzetten',
    owner: 'Samen',
    status: 'Backlog',
    priority: 'P2',
    roadmapPhase: 'Backlog',
    projectArea: 'Documentatie',
    nextAction: 'Kies vaste dag en tijd voor ChatManta planning.',
    impact: 'Middel',
    effort: 'Klein',
  },

  // -----------------------------------------------------------------------
  // Nog toe te wijzen
  // -----------------------------------------------------------------------
  {
    title: 'ChatManta README bijwerken',
    owner: 'Nog toe te wijzen',
    status: 'Backlog',
    priority: 'P3',
    roadmapPhase: 'v1',
    projectArea: 'Documentatie',
    nextAction: 'Documenteer hoe de app lokaal draait.',
    impact: 'Laag',
    effort: 'Klein',
  },
  {
    title: 'Branding opties voorbereiden',
    owner: 'Nog toe te wijzen',
    status: 'Backlog',
    priority: 'P3',
    roadmapPhase: 'v2',
    projectArea: 'Product / UX',
    nextAction: 'Bepaal welke brandinginstellingen later nodig zijn.',
    impact: 'Laag',
    effort: 'Middel',
  },
  {
    title: 'Analytics ideeën verzamelen',
    owner: 'Nog toe te wijzen',
    status: 'Backlog',
    priority: 'P3',
    roadmapPhase: 'v2',
    projectArea: 'Dashboard',
    nextAction: 'Verzamel ideeën voor nuttige klantanalytics.',
    impact: 'Laag',
    effort: 'Klein',
  },
];
